"""Verify the actual PDFs generated by tests/snapshot-pdf.test.ts.

Run the Vitest file first, then run this script with Python + pdfplumber.
No production credentials, browser session or customer data are used.
"""
from pathlib import Path
import pdfplumber

root = Path(__file__).resolve().parent.parent / "artifacts" / "snapshot-pdf"
for name in ("sample", "large", "empty-stale", "oversized", "unicode", "isolated", "comparison"):
    with pdfplumber.open(root / f"{name}.pdf") as document:
        text = "\n".join(page.extract_text() or "" for page in document.pages)
        for required in ("Origem dos dados", "snapshot-confirmado-123", "2026-10-04T12:34:56Z"):
            assert required in text, (name, required)
        for number, page in enumerate(document.pages, 1):
            assert "iGrow Reports" in (page.extract_text() or ""), (name, number, "running header")
            for char in page.chars:
                assert 49 <= char["x0"] <= char["x1"] <= 546, (name, number, "horizontal overflow")
                assert 20 <= char["top"] <= char["bottom"] <= 832, (name, number, "vertical overflow")
        if name not in ("empty-stale", "oversized"):
            for required in ("123456789012345678.12345678", "2.19000001%", "Zero confirmado", "Indisponível", "Não confirmado"):
                assert required in text, (name, required)
        if name == "large":
            assert all(f"ID: ad-{number} |" in text for number in range(1, 62)), "Missing entity"
        if name == "empty-stale":
            assert "Aguardando atualização" in text and "sem entidades" in text
            assert "BRL 0" not in text
        if name == "unicode":
            assert "Καμπάνια" in text and "Кампания" in text
        if name == "isolated":
            assert "CONTA QUE NÃO DEVE APARECER" not in text
            assert "NÍVEL QUE NÃO DEVE APARECER" not in text
        if name == "comparison":
            text = " ".join(text.split())
            for required in ("previous-confirmed-snapshot", "28/09/2026 a 30/09/2026", "Anterior:", "Diferença: 0", "o valor anterior é zero", "seis casas"):
                assert required in text, (name, required)
        print(f"{name}: {len(document.pages)} pages; exact values, provenance and layout bounds approved")
